import { iPokemon } from ".";

export const newPokemons: iPokemon[] = [
  {
    Pokemon: "Venusaur",
    Rarity: "Epic",
    Number: 3,
    Type01: "Grass",
    Type02: "Poison",
  },
  {
    Pokemon: "Charizard",
    Rarity: "Epic",
    Number: 6,
    Type01: "Fire",
    Type02: "Flying",
  },
  {
    Pokemon: "Blastoise",
    Rarity: "Epic",
    Number: 9,
    Type01: "Water",
    Type02: "null",
  },
  {
    Pokemon: "Butterfree",
    Rarity: "Epic",
    Number: 12,
    Type01: "Bug",
    Type02: "Flying",
  },
  {
    Pokemon: "Beedrill",
    Rarity: "Epic",
    Number: 15,
    Type01: "Bug",
    Type02: "Poison",
  },
  {
    Pokemon: "Pidgeot",
    Rarity: "Epic",
    Number: 18,
    Type01: "Normal",
    Type02: "Flying",
  },
  {
    Pokemon: "Nidoqueen",
    Rarity: "Epic",
    Number: 31,
    Type01: "Poison",
    Type02: "Ground",
  },
  {
    Pokemon: "Nidoking",
    Rarity: "Epic",
    Number: 34,
    Type01: "Poison",
    Type02: "Ground",
  },
  {
    Pokemon: "Vileplume",
    Rarity: "Epic",
    Number: 45,
    Type01: "Grass",
    Type02: "Poison",
  },
  {
    Pokemon: "Poliwrath",
    Rarity: "Epic",
    Number: 62,
    Type01: "Water",
    Type02: "Fighting",
  },
  {
    Pokemon: "Alakazam",
    Rarity: "Epic",
    Number: 65,
    Type01: "Psychic",
    Type02: "null",
  },
  {
    Pokemon: "Machamp",
    Rarity: "Epic",
    Number: 68,
    Type01: "Fighting",
    Type02: "null",
  },
  {
    Pokemon: "Victreebel",
    Rarity: "Epic",
    Number: 71,
    Type01: "Grass",
    Type02: "Poison",
  },
  {
    Pokemon: "Golem",
    Rarity: "Epic",
    Number: 76,
    Type01: "Rock",
    Type02: "Ground",
  },
  {
    Pokemon: "Gengar",
    Rarity: "Epic",
    Number: 94,
    Type01: "Ghost",
    Type02: "Poison",
  },
  {
    Pokemon: "Articuno",
    Rarity: "Legendary",
    Number: 144,
    Type01: "Ice",
    Type02: "Flying",
  },
  {
    Pokemon: "Zapdos",
    Rarity: "Legendary",
    Number: 145,
    Type01: "Eletric",
    Type02: "Flying",
  },
  {
    Pokemon: "Moltres",
    Rarity: "Legendary",
    Number: 146,
    Type01: "Fire",
    Type02: "Flying",
  },
  {
    Pokemon: "Dratini",
    Rarity: "Rare",
    Number: 147,
    Type01: "Dragon",
    Type02: "null",
  },
  {
    Pokemon: "Dragonair",
    Rarity: "Epic",
    Number: 148,
    Type01: "Dragon",
    Type02: "null",
  },
  {
    Pokemon: "Dragonite",
    Rarity: "Legendary",
    Number: 149,
    Type01: "Dragon",
    Type02: "Flying",
  },
  {
    Pokemon: "Mewtwo",
    Rarity: "Legendary",
    Number: 150,
    Type01: "Psychic",
    Type02: "null",
  },
  {
    Pokemon: "Mew",
    Rarity: "Legendary",
    Number: 151,
    Type01: "Psychic",
    Type02: "null",
  },
];
